server:
  port: 8098
  devtools:
    restart:
      enabled: true # 设置开启热部署
      additional-paths: src/main/java # 指定热部署的目录
      exclude: test/** # 指定目录不更新
logging:
  config: classpath:logback-custom.xml
  level:
    cn:
      jtoss:
        debug
    org:
      springframework:
        boot:
          autoconfigure: info

